extern const GeoLayout bitdw_area_1_geo[];
extern const GeoLayout bitdw_area_1[];
extern const Collision bitdw_area_1_collision[];
extern const MacroObject bitdw_area_1_macro_objs[];
extern Lights1 bitdw_dl_nonslip_layer1_area1_lights;
extern u8 bitdw_dl__3C96C6A_c_ci4[];
extern u8 bitdw_dl__3C96C6A_c_ci4_pal_rgba16[];
extern Vtx bitdw_dl_Shape_IndexedFaceSet_020_Shape_IndexedFaceSet_003_mesh_layer_1_vtx_0[329];
extern Gfx bitdw_dl_Shape_IndexedFaceSet_020_Shape_IndexedFaceSet_003_mesh_layer_1_tri_0[];
extern Gfx mat_bitdw_dl_nonslip_layer1_area1[];
extern Gfx mat_revert_bitdw_dl_nonslip_layer1_area1[];
extern Gfx bitdw_dl_Shape_IndexedFaceSet_020_Shape_IndexedFaceSet_003_mesh_layer_1[];
extern Gfx bitdw_dl_material_revert_render_settings[];
